[[redirects]]
  from = "https://melodic-rabanadas-8ccf01.netlify.app/"
  to = "https://strapi-backend-production-abca.up.railway.app"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"